@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.ttmpdiscordbot.javascript;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;