@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.ttmpdiscordbot.api.wrapper;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;