@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.ttmpdiscordbot.ast.textcomponent;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;