@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.ttmpdiscordbot.ast.node;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;