@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.ttmpdiscordbot.ast.parser;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;